name: ZeaBigData
description:  A platform for NGS data curation

sass:
  sass_dir: assets/css/_sass
  style: :compressed

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

url: "https://zeabigdata.github.io/zeasite/"
permalink: /:year/:month/:title/
owner:
    name: #
    twitter: #
    github: #
    disqus_shortname: #

ga_id: #
ga_username: #

timezone: Africa/Accra

baseurl:            ""
