name: ZeaBigData
description:  A platform for NGS data curation

sass:
  sass_dir: assets/css/_sass
  style: :compressed

redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

url: ""
permalink: /:year/:month/:title/
owner:
    name: #
    twitter: #
    github: ZeaBigData
    disqus_shortname: yangjl

ga_id: #
ga_username: #

timezone: Africa/Accra

baseurl:            ""

comments:
  disqus:
    short_name: yangjl
    api_key:    YOUR-DISQUS-PUBLIC-KEY-HERE
